name: github-package-manager
version: 0.2.0
summary: The Linux package manager built on GitHub
description: |
  GPM (GitHub Package Manager) is a package manager built on GitHub. Using GitHub repositories as packages, it's effortless to put a package on gpm.

confinement: devmode

parts:
  gpm:
    plugin: dump
    source: https://github.com/cbrnrd/gpm/releases/download/0.2.0/gpm_0.2.0.zip

apps:
  gpm:
    command: gpm
